### ISSUE TITLE
Unresponsive Black Screen

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Hexxah/CoC-MOD-Android-Build#10]
Often times,with freezing

**Comment by Oxdeception** [comment]
Please include with issues:* Mod name* Mod version* Steps to reproduce* How often the issue occursOn 28 Feb 2019 13:04, jakerockz97 <notifications@github.com> wrote:Often times,with freezing

**Comment by Oxdeception** [comment]
Please include with issues: 
* Mod name 
* Mod version 
* Steps to reproduce 
* How often the issue occurs

**Comment by Oxdeception** [comment]
Closing - 24 days with no response
