### ISSUE TITLE
App is just giving the black screen.

### ISSUE THREAD

**Issue by Adim2P** [Hexxah/CoC-MOD-Android-Build#11]
Currently happy I found this github page with the Xianxia port on android but to no avail the game just throws me a black screen currently using the latest build of the xianxia mode doesn't really do anything, on startup just gives a blackscreen any fix? I'm using the ARM apk x86 is not compatible for me.

**Comment by Oxdeception** [comment]
This requires a code fix on the mod itself. The workaround until that is done is to wait and ignore any app not responding screens that appear. 

#6 for more information and links to the fixes that were applied to the other mods.
