### ISSUE TITLE
"App not installed" CoC Revamp

### ISSUE THREAD

**Issue by MisterTwelve** [Hexxah/CoC-MOD-Android-Build#12]
I've been using the android version of CoC for the longest time, both the vanilla and revamp mod, and never had issues. But I also haven't used a new version in a year or two (my current revamp is 1.4.13). **I tried to update to the newest version but when I try to (both arm and x86) it gives me the message App not installed.**

- It's also not an issue that would be solved by uninstalling the old one, as I tried to install the Xianxia version (which I've never played) just to test and that one also gave me the same error.
- Another thing to add on is it's not a universal issue as other apps I've installed through apks didn't give me any problems.
For reference my phone is a Galaxy S8 running the latest version (to my knowledge) of Android, and is not rooted.

Any help would be appreciated, thanks, and just let me know if any other information is needed. I really love playing CoC in my free time on my phone so I'd love to get the newest version working. (I'll try to check this daily but I apologize ahead of time if any of my responses are late).

**Comment by DragonessLover** [comment]
What browser are you using to download the apk?

**Comment by MisterTwelve** [comment]
I tried both the default internet browser and CM Browser, those are the only two I've ever used.
--Edit--
I also just tried using Firefox and it still gives me the error.

**Comment by DragonessLover** [comment]
I'm not familiar with the CM browser, but you might try using Firefox, I've had the same issue when downloading some apks with Chrome and Chrome-based browsers, but using Firefox to download the apk seems to circumvent the issue pretty well.

**Comment by MisterTwelve** [comment]
I did install and try Firefox and it still gave me the same problem.

**Comment by Oxdeception** [comment]
Do you have enough space on your phone?

**Comment by MisterTwelve** [comment]
Yes, more than 20gb left.

**Comment by Hexxah** [comment]
Does this only happen with new version or even older ones?

Some things to try:
How are you installing? Try using a file explorer (ES Explorer) to launch the apk for install.
Make sure Unknown Source/Apps (Non Playstore) are allowed.
TEMPORARILY disable Play Protect in Playstore -> Settings -> Protect My Updates.

**Comment by MisterTwelve** [comment]
I tried both launching the apk through the default file browser and ES Explorer, same results.
I do have unknown sources allowed, and my play protect is disabled (because of other modded apps I use).

It seems like it's only specific older ones that work. Testing with Xinxia since I don't want to corrupt my currently working version of Revamp, the newest one that would work when I tried installing just now is Xinxia 8.16 (listed as Xinxia 0.8g2 from Nov 2, 2017). And only the arm version worked despite my phone being capable of using x86.

Another thing to add is this version that worked is even older than my working version of Revamp, when I tried installing the version of Xinxia that was released around the same time as Revamp 1.4.13 it would give me the error.

**Comment by DragonessLover** [comment]
Just to clarify, arm is actually the better version as it is the Android equivalent of 64-bit, whereas x86 is universally known to be 32-bit.

**Comment by MisterTwelve** [comment]
> Just to clarify, arm is actually the better version as it is the Android equivalent of 64-bit, whereas x86 is universally known to be 32-bit.

Ah, I had heard the opposite. Thanks for that info.

**Comment by Oxdeception** [comment]
Both the x86 and ARM APKs are 32 bit. There are also 64 bit CPUs for both ARM (ARM64) and x86 (x86-64). 

Neither APK should be considered better than the other, they are simply compiled for the different architectures. Which APK you should use would be based on your phone's CPU.

**Comment by Hexxah** [comment]
Pretty much what Ox said sums it up. The S8 uses an arm CPU so use that version.

 I'll look into it changed anything between those versions when I get some time. Also if you have discord contact me there since I rarely check GitHub and will be able to respond much quicker.

**Comment by MisterTwelve** [comment]
Got it.

Much appreciated, I haven't the faintest idea what might be causing the issue but hopefully it's something simple. And yes I do have discord but I'm not sure where to find you, if there's one I should join or what.

**Comment by Hexxah** [comment]
https://discord.gg/KVPGEM5 Here's the CoC discord, both Ox and I can be found on it. 

I think I might have found the reason why you cant upgrade from 1.13. Just gonna need to debug a bit more before I'm completely sure. 
But im not sure about why you cant install newer version of Xianxia also if yo could try the arm version here and let me know https://github.com/Oxdeception/Corruption-of-Champions/releases/tag/0.0.3-EJ
