### ISSUE TITLE
Freeze issue

### ISSUE THREAD

**Issue by GameMasterPo** [Hexxah/CoC-MOD-Android-Build#13]
I encountered a bug where if you have the shield maiden and you acquire the basic leadership Perk it states the shield maiden is'nt in your party and when you bring in another person say one of your lovers and go into battle or into the dungeon at the soul cultivator town the game freezes after you click next to continue the battlethis is happened multiple times just wanted to bring this to your attention so that in the next update it isn't an issue or to help you decide to make a patch for this version to fix it sorry for bothering you and I hope you fix this bug. Furthermore, this is for the mod Xianxia and I encounted this in the Android version don't know if the PC version has the same problem but again sorry to bother you.

**Comment by Oxdeception** [comment]
This should be reported on the mod's GitHub page. I don't believe it is an issue with the APK.

**Comment by GameMasterPo** [comment]
I'm sorry for reposting issue I didn't get you the email till now but I
will sure do that
