### ISSUE TITLE
Powershell necessary or nah?

### ISSUE THREAD

**Issue by NatKiasu** [Hexxah/CoC-MOD-Android-Build#2]
You mentiones running the start.ps1 file on Powershell, it that absolutely necessary or can that step be skipped ? Since Powershell is a paid app, and I'm finding downloading the free apk version impossible, so...

**Comment by Hexxah** [comment]
PowerShell is by default built in Windows 7 and above. It is only needed if you want to compile your own build and even then you could just run most cammands in cmd.
Apks can be found on the release page https://github.com/Hexxah/CoC-MOD-Android-Build/releases
