### ISSUE TITLE
Save to File Location

### ISSUE THREAD

**Issue by Hexxah** [Hexxah/CoC-MOD-Android-Build#3]
So I got a request asking if it would be possible to change the save to file locations for each mod so that they save and load from a different location do something like /data/revamp and /data/xianxia. Let me know what you guys want will implement in next versions depending on votes.

[![](https://api.gh-polls.com/poll/01C0C9X6K3CAR2QF81EB54N2S5/No%20need%20for%20changes)](https://api.gh-polls.com/poll/01C0C9X6K3CAR2QF81EB54N2S5/No%20need%20for%20changes/vote)
[![](https://api.gh-polls.com/poll/01C0C9X6K3CAR2QF81EB54N2S5/Both%20Revamp%20and%20Xianxia%20together%20but%20separate%20from%20original)](https://api.gh-polls.com/poll/01C0C9X6K3CAR2QF81EB54N2S5/Both%20Revamp%20and%20Xianxia%20together%20but%20separate%20from%20original/vote)
[![](https://api.gh-polls.com/poll/01C0C9X6K3CAR2QF81EB54N2S5/Seperate%20for%20each%20version.)](https://api.gh-polls.com/poll/01C0C9X6K3CAR2QF81EB54N2S5/Seperate%20for%20each%20version./vote)

**Comment by Oxdeception** [comment]
Changing this save location does require changing a line in the base game's code, to the best of my knowledge.
