### ISSUE TITLE
Revamp installing as Xianxia

### ISSUE THREAD

**Issue by DragonessLover** [Hexxah/CoC-MOD-Android-Build#4]
The latest upload the Revamp mod is installing itself with the Xianxia app name, even though it's actually the Revamp edition, leaving me with Revamp 1.4.10b labeled as Revamp Mod and Revamp 1.4.11 labeled as Xianxia Mod.

**Comment by Hexxah** [comment]
Thanks for noticing that. I had renamed my xianxia xml to revamp for some testing and forgot to change it back. I've uploaded the fixed apks.

**Comment by DragonessLover** [comment]
That's fixed now, thank you :)
