### ISSUE TITLE
will not open

### ISSUE THREAD

**Issue by Worthey** [Hexxah/CoC-MOD-Android-Build#6]
i downloaded the arm apk on both chrome and firefox and it wi install but all i get when i go to open it i a black screen and after a couple minutes and app s not responding. am i doing soemthing wrong? plz help

**Comment by Oxdeception** [comment]
The APKs take a long time to load the first time, often you need to wait through the not responding screen for several minutes. I'm not sure if there's any way to really fix this on this end.

**Comment by Oxdeception** [comment]
Closing this issue as load times have been patched.
