### ISSUE TITLE
Marble's Milk

### ISSUE THREAD

**Issue by DragonessLover** [Hexxah/CoC-MOD-Android-Build#8]
Something is causing the PC to drink from Marble once at 6am each morning, and then again at 7am, resulting in a total of +4 corruption per day when corruption is relatively low, instead of only +2.

**Comment by Oxdeception** [comment]
Please attempt to replicate this on the same desktop version of whichever mod you are using, and if the issue exists there also please post an issue on that mod's GitHub page.

This does not seem it is related to the APK. This issue can be reopened if it is determined to be specific to an APK feature.
